name: cola_espera_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^20.3.47
  cupertino_icons: ^1.0.8
  simple_animations: ^5.0.0+3
  supercharged: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/university_logo.png